/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_ENDDEVICEPROTOCOL_ENDDEVICEPROTOCOL_PB_H_INCLUDED
#define PB_ENDDEVICEPROTOCOL_ENDDEVICEPROTOCOL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _EndDeviceProtocol_ExpressionInstructions {
    EndDeviceProtocol_ExpressionInstructions_CONST = 0,
    EndDeviceProtocol_ExpressionInstructions_VAR = 1,
    EndDeviceProtocol_ExpressionInstructions_AND = 2,
    EndDeviceProtocol_ExpressionInstructions_OR = 3,
    EndDeviceProtocol_ExpressionInstructions_NOT = 4,
    EndDeviceProtocol_ExpressionInstructions_LT = 5,
    EndDeviceProtocol_ExpressionInstructions_GT = 6,
    EndDeviceProtocol_ExpressionInstructions_EQ = 7,
    EndDeviceProtocol_ExpressionInstructions_ADD = 8,
    EndDeviceProtocol_ExpressionInstructions_SUB = 9,
    EndDeviceProtocol_ExpressionInstructions_MUL = 10,
    EndDeviceProtocol_ExpressionInstructions_DIV = 11,
    EndDeviceProtocol_ExpressionInstructions_MOD = 12
} EndDeviceProtocol_ExpressionInstructions;

typedef enum _EndDeviceProtocol_WindowAggregationType {
    EndDeviceProtocol_WindowAggregationType_MIN = 0,
    EndDeviceProtocol_WindowAggregationType_MAX = 1,
    EndDeviceProtocol_WindowAggregationType_SUM = 2,
    EndDeviceProtocol_WindowAggregationType_AVG = 3,
    EndDeviceProtocol_WindowAggregationType_COUNT = 4
} EndDeviceProtocol_WindowAggregationType;

typedef enum _EndDeviceProtocol_WindowSizeType {
    EndDeviceProtocol_WindowSizeType_TIMEBASED = 0,
    EndDeviceProtocol_WindowSizeType_COUNTBASED = 1
} EndDeviceProtocol_WindowSizeType;

/* Struct definitions */
typedef struct _EndDeviceProtocol_Data {
    pb_size_t which_data;
    union {
        EndDeviceProtocol_ExpressionInstructions instruction;
        uint32_t _uint8;
        uint32_t _uint16;
        uint32_t _uint32;
        uint64_t _uint64;
        int32_t _int8;
        int32_t _int16;
        int32_t _int32;
        int64_t _int64;
        float _float;
        double _double;
    } data;
} EndDeviceProtocol_Data;

typedef struct _EndDeviceProtocol_Output {
    pb_callback_t responses;
} EndDeviceProtocol_Output;

typedef struct _EndDeviceProtocol_Output_QueryResponse {
    int32_t id;
    pb_callback_t response;
} EndDeviceProtocol_Output_QueryResponse;

typedef struct _EndDeviceProtocol_Expression {
    pb_callback_t instructions;
} EndDeviceProtocol_Expression;

typedef struct _EndDeviceProtocol_MapOperation {
    pb_callback_t function;
    int32_t attribute;
} EndDeviceProtocol_MapOperation;

typedef struct _EndDeviceProtocol_FilterOperation {
    pb_callback_t predicate;
} EndDeviceProtocol_FilterOperation;

typedef struct _EndDeviceProtocol_WindowOperation {
    int32_t size;
    EndDeviceProtocol_WindowSizeType sizeType;
    EndDeviceProtocol_WindowAggregationType aggregationType;
    int32_t startAttribute;
    int32_t endAttribute;
    int32_t resultAttribute;
    int32_t readAttribute;
} EndDeviceProtocol_WindowOperation;

typedef struct _EndDeviceProtocol_Operation {
    pb_size_t which_operation;
    union {
        EndDeviceProtocol_MapOperation map;
        EndDeviceProtocol_FilterOperation filter;
        EndDeviceProtocol_WindowOperation window;
    } operation;
} EndDeviceProtocol_Operation;

typedef struct _EndDeviceProtocol_Query {
    /* bytes resultType = 1; //For some reason minipb breaks if I make this a repeated enum or int32 */
    pb_callback_t operations;
} EndDeviceProtocol_Query;

typedef struct _EndDeviceProtocol_Message {
    pb_callback_t queries;
} EndDeviceProtocol_Message;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _EndDeviceProtocol_ExpressionInstructions_MIN EndDeviceProtocol_ExpressionInstructions_CONST
#define _EndDeviceProtocol_ExpressionInstructions_MAX EndDeviceProtocol_ExpressionInstructions_MOD
#define _EndDeviceProtocol_ExpressionInstructions_ARRAYSIZE ((EndDeviceProtocol_ExpressionInstructions)(EndDeviceProtocol_ExpressionInstructions_MOD+1))

#define _EndDeviceProtocol_WindowAggregationType_MIN EndDeviceProtocol_WindowAggregationType_MIN
#define _EndDeviceProtocol_WindowAggregationType_MAX EndDeviceProtocol_WindowAggregationType_COUNT
#define _EndDeviceProtocol_WindowAggregationType_ARRAYSIZE ((EndDeviceProtocol_WindowAggregationType)(EndDeviceProtocol_WindowAggregationType_COUNT+1))

#define _EndDeviceProtocol_WindowSizeType_MIN EndDeviceProtocol_WindowSizeType_TIMEBASED
#define _EndDeviceProtocol_WindowSizeType_MAX EndDeviceProtocol_WindowSizeType_COUNTBASED
#define _EndDeviceProtocol_WindowSizeType_ARRAYSIZE ((EndDeviceProtocol_WindowSizeType)(EndDeviceProtocol_WindowSizeType_COUNTBASED+1))

#define EndDeviceProtocol_Data_data_instruction_ENUMTYPE EndDeviceProtocol_ExpressionInstructions






#define EndDeviceProtocol_WindowOperation_sizeType_ENUMTYPE EndDeviceProtocol_WindowSizeType
#define EndDeviceProtocol_WindowOperation_aggregationType_ENUMTYPE EndDeviceProtocol_WindowAggregationType





/* Initializer values for message structs */
#define EndDeviceProtocol_Data_init_default      {0, {_EndDeviceProtocol_ExpressionInstructions_MIN}}
#define EndDeviceProtocol_Output_init_default    {{{NULL}, NULL}}
#define EndDeviceProtocol_Output_QueryResponse_init_default {0, {{NULL}, NULL}}
#define EndDeviceProtocol_Expression_init_default {{{NULL}, NULL}}
#define EndDeviceProtocol_MapOperation_init_default {{{NULL}, NULL}, 0}
#define EndDeviceProtocol_FilterOperation_init_default {{{NULL}, NULL}}
#define EndDeviceProtocol_WindowOperation_init_default {0, _EndDeviceProtocol_WindowSizeType_MIN, _EndDeviceProtocol_WindowAggregationType_MIN, 0, 0, 0, 0}
#define EndDeviceProtocol_Operation_init_default {0, {EndDeviceProtocol_MapOperation_init_default}}
#define EndDeviceProtocol_Query_init_default     {{{NULL}, NULL}}
#define EndDeviceProtocol_Message_init_default   {{{NULL}, NULL}}
#define EndDeviceProtocol_Data_init_zero         {0, {_EndDeviceProtocol_ExpressionInstructions_MIN}}
#define EndDeviceProtocol_Output_init_zero       {{{NULL}, NULL}}
#define EndDeviceProtocol_Output_QueryResponse_init_zero {0, {{NULL}, NULL}}
#define EndDeviceProtocol_Expression_init_zero   {{{NULL}, NULL}}
#define EndDeviceProtocol_MapOperation_init_zero {{{NULL}, NULL}, 0}
#define EndDeviceProtocol_FilterOperation_init_zero {{{NULL}, NULL}}
#define EndDeviceProtocol_WindowOperation_init_zero {0, _EndDeviceProtocol_WindowSizeType_MIN, _EndDeviceProtocol_WindowAggregationType_MIN, 0, 0, 0, 0}
#define EndDeviceProtocol_Operation_init_zero    {0, {EndDeviceProtocol_MapOperation_init_zero}}
#define EndDeviceProtocol_Query_init_zero        {{{NULL}, NULL}}
#define EndDeviceProtocol_Message_init_zero      {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define EndDeviceProtocol_Data_instruction_tag   1
#define EndDeviceProtocol_Data__uint8_tag        2
#define EndDeviceProtocol_Data__uint16_tag       3
#define EndDeviceProtocol_Data__uint32_tag       4
#define EndDeviceProtocol_Data__uint64_tag       5
#define EndDeviceProtocol_Data__int8_tag         6
#define EndDeviceProtocol_Data__int16_tag        7
#define EndDeviceProtocol_Data__int32_tag        8
#define EndDeviceProtocol_Data__int64_tag        9
#define EndDeviceProtocol_Data__float_tag        10
#define EndDeviceProtocol_Data__double_tag       11
#define EndDeviceProtocol_Output_responses_tag   1
#define EndDeviceProtocol_Output_QueryResponse_id_tag 1
#define EndDeviceProtocol_Output_QueryResponse_response_tag 2
#define EndDeviceProtocol_Expression_instructions_tag 1
#define EndDeviceProtocol_MapOperation_function_tag 1
#define EndDeviceProtocol_MapOperation_attribute_tag 2
#define EndDeviceProtocol_FilterOperation_predicate_tag 1
#define EndDeviceProtocol_WindowOperation_size_tag 1
#define EndDeviceProtocol_WindowOperation_sizeType_tag 2
#define EndDeviceProtocol_WindowOperation_aggregationType_tag 3
#define EndDeviceProtocol_WindowOperation_startAttribute_tag 4
#define EndDeviceProtocol_WindowOperation_endAttribute_tag 5
#define EndDeviceProtocol_WindowOperation_resultAttribute_tag 6
#define EndDeviceProtocol_WindowOperation_readAttribute_tag 7
#define EndDeviceProtocol_Operation_map_tag      1
#define EndDeviceProtocol_Operation_filter_tag   2
#define EndDeviceProtocol_Operation_window_tag   3
#define EndDeviceProtocol_Query_operations_tag   1
#define EndDeviceProtocol_Message_queries_tag    1

/* Struct field encoding specification for nanopb */
#define EndDeviceProtocol_Data_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    UENUM,    (data,instruction,data.instruction),   1) \
X(a, STATIC,   ONEOF,    UINT32,   (data,_uint8,data._uint8),   2) \
X(a, STATIC,   ONEOF,    UINT32,   (data,_uint16,data._uint16),   3) \
X(a, STATIC,   ONEOF,    UINT32,   (data,_uint32,data._uint32),   4) \
X(a, STATIC,   ONEOF,    UINT64,   (data,_uint64,data._uint64),   5) \
X(a, STATIC,   ONEOF,    SINT32,   (data,_int8,data._int8),   6) \
X(a, STATIC,   ONEOF,    SINT32,   (data,_int16,data._int16),   7) \
X(a, STATIC,   ONEOF,    SINT32,   (data,_int32,data._int32),   8) \
X(a, STATIC,   ONEOF,    SINT64,   (data,_int64,data._int64),   9) \
X(a, STATIC,   ONEOF,    FLOAT,    (data,_float,data._float),  10) \
X(a, STATIC,   ONEOF,    DOUBLE,   (data,_double,data._double),  11)
#define EndDeviceProtocol_Data_CALLBACK NULL
#define EndDeviceProtocol_Data_DEFAULT NULL

#define EndDeviceProtocol_Output_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  responses,         1)
#define EndDeviceProtocol_Output_CALLBACK pb_default_field_callback
#define EndDeviceProtocol_Output_DEFAULT NULL
#define EndDeviceProtocol_Output_responses_MSGTYPE EndDeviceProtocol_Output_QueryResponse

#define EndDeviceProtocol_Output_QueryResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    id,                1) \
X(a, CALLBACK, REPEATED, MESSAGE,  response,          2)
#define EndDeviceProtocol_Output_QueryResponse_CALLBACK pb_default_field_callback
#define EndDeviceProtocol_Output_QueryResponse_DEFAULT NULL
#define EndDeviceProtocol_Output_QueryResponse_response_MSGTYPE EndDeviceProtocol_Data

#define EndDeviceProtocol_Expression_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  instructions,      1)
#define EndDeviceProtocol_Expression_CALLBACK pb_default_field_callback
#define EndDeviceProtocol_Expression_DEFAULT NULL
#define EndDeviceProtocol_Expression_instructions_MSGTYPE EndDeviceProtocol_Data

#define EndDeviceProtocol_MapOperation_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  function,          1) \
X(a, STATIC,   SINGULAR, INT32,    attribute,         2)
#define EndDeviceProtocol_MapOperation_CALLBACK pb_default_field_callback
#define EndDeviceProtocol_MapOperation_DEFAULT NULL
#define EndDeviceProtocol_MapOperation_function_MSGTYPE EndDeviceProtocol_Data

#define EndDeviceProtocol_FilterOperation_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  predicate,         1)
#define EndDeviceProtocol_FilterOperation_CALLBACK pb_default_field_callback
#define EndDeviceProtocol_FilterOperation_DEFAULT NULL
#define EndDeviceProtocol_FilterOperation_predicate_MSGTYPE EndDeviceProtocol_Data

#define EndDeviceProtocol_WindowOperation_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    size,              1) \
X(a, STATIC,   SINGULAR, UENUM,    sizeType,          2) \
X(a, STATIC,   SINGULAR, UENUM,    aggregationType,   3) \
X(a, STATIC,   SINGULAR, INT32,    startAttribute,    4) \
X(a, STATIC,   SINGULAR, INT32,    endAttribute,      5) \
X(a, STATIC,   SINGULAR, INT32,    resultAttribute,   6) \
X(a, STATIC,   SINGULAR, INT32,    readAttribute,     7)
#define EndDeviceProtocol_WindowOperation_CALLBACK NULL
#define EndDeviceProtocol_WindowOperation_DEFAULT NULL

#define EndDeviceProtocol_Operation_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (operation,map,operation.map),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (operation,filter,operation.filter),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (operation,window,operation.window),   3)
#define EndDeviceProtocol_Operation_CALLBACK NULL
#define EndDeviceProtocol_Operation_DEFAULT NULL
#define EndDeviceProtocol_Operation_operation_map_MSGTYPE EndDeviceProtocol_MapOperation
#define EndDeviceProtocol_Operation_operation_filter_MSGTYPE EndDeviceProtocol_FilterOperation
#define EndDeviceProtocol_Operation_operation_window_MSGTYPE EndDeviceProtocol_WindowOperation

#define EndDeviceProtocol_Query_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  operations,        1)
#define EndDeviceProtocol_Query_CALLBACK pb_default_field_callback
#define EndDeviceProtocol_Query_DEFAULT NULL
#define EndDeviceProtocol_Query_operations_MSGTYPE EndDeviceProtocol_MapOperation

#define EndDeviceProtocol_Message_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  queries,           1)
#define EndDeviceProtocol_Message_CALLBACK pb_default_field_callback
#define EndDeviceProtocol_Message_DEFAULT NULL
#define EndDeviceProtocol_Message_queries_MSGTYPE EndDeviceProtocol_Query

extern const pb_msgdesc_t EndDeviceProtocol_Data_msg;
extern const pb_msgdesc_t EndDeviceProtocol_Output_msg;
extern const pb_msgdesc_t EndDeviceProtocol_Output_QueryResponse_msg;
extern const pb_msgdesc_t EndDeviceProtocol_Expression_msg;
extern const pb_msgdesc_t EndDeviceProtocol_MapOperation_msg;
extern const pb_msgdesc_t EndDeviceProtocol_FilterOperation_msg;
extern const pb_msgdesc_t EndDeviceProtocol_WindowOperation_msg;
extern const pb_msgdesc_t EndDeviceProtocol_Operation_msg;
extern const pb_msgdesc_t EndDeviceProtocol_Query_msg;
extern const pb_msgdesc_t EndDeviceProtocol_Message_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define EndDeviceProtocol_Data_fields &EndDeviceProtocol_Data_msg
#define EndDeviceProtocol_Output_fields &EndDeviceProtocol_Output_msg
#define EndDeviceProtocol_Output_QueryResponse_fields &EndDeviceProtocol_Output_QueryResponse_msg
#define EndDeviceProtocol_Expression_fields &EndDeviceProtocol_Expression_msg
#define EndDeviceProtocol_MapOperation_fields &EndDeviceProtocol_MapOperation_msg
#define EndDeviceProtocol_FilterOperation_fields &EndDeviceProtocol_FilterOperation_msg
#define EndDeviceProtocol_WindowOperation_fields &EndDeviceProtocol_WindowOperation_msg
#define EndDeviceProtocol_Operation_fields &EndDeviceProtocol_Operation_msg
#define EndDeviceProtocol_Query_fields &EndDeviceProtocol_Query_msg
#define EndDeviceProtocol_Message_fields &EndDeviceProtocol_Message_msg

/* Maximum encoded size of messages (where known) */
/* EndDeviceProtocol_Output_size depends on runtime parameters */
/* EndDeviceProtocol_Output_QueryResponse_size depends on runtime parameters */
/* EndDeviceProtocol_Expression_size depends on runtime parameters */
/* EndDeviceProtocol_MapOperation_size depends on runtime parameters */
/* EndDeviceProtocol_FilterOperation_size depends on runtime parameters */
/* EndDeviceProtocol_Operation_size depends on runtime parameters */
/* EndDeviceProtocol_Query_size depends on runtime parameters */
/* EndDeviceProtocol_Message_size depends on runtime parameters */
#define EndDeviceProtocol_Data_size              11
#define EndDeviceProtocol_WindowOperation_size   59

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
