/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: EndDeviceProtocol.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "EndDeviceProtocol.pb-c.h"
void   end_device_protocol__data__init
                     (EndDeviceProtocol__Data         *message)
{
  static const EndDeviceProtocol__Data init_value = END_DEVICE_PROTOCOL__DATA__INIT;
  *message = init_value;
}
size_t end_device_protocol__data__get_packed_size
                     (const EndDeviceProtocol__Data *message)
{
  assert(message->base.descriptor == &end_device_protocol__data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t end_device_protocol__data__pack
                     (const EndDeviceProtocol__Data *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &end_device_protocol__data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t end_device_protocol__data__pack_to_buffer
                     (const EndDeviceProtocol__Data *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &end_device_protocol__data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EndDeviceProtocol__Data *
       end_device_protocol__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EndDeviceProtocol__Data *)
     protobuf_c_message_unpack (&end_device_protocol__data__descriptor,
                                allocator, len, data);
}
void   end_device_protocol__data__free_unpacked
                     (EndDeviceProtocol__Data *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &end_device_protocol__data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   end_device_protocol__output__query_response__init
                     (EndDeviceProtocol__Output__QueryResponse         *message)
{
  static const EndDeviceProtocol__Output__QueryResponse init_value = END_DEVICE_PROTOCOL__OUTPUT__QUERY_RESPONSE__INIT;
  *message = init_value;
}
void   end_device_protocol__output__init
                     (EndDeviceProtocol__Output         *message)
{
  static const EndDeviceProtocol__Output init_value = END_DEVICE_PROTOCOL__OUTPUT__INIT;
  *message = init_value;
}
size_t end_device_protocol__output__get_packed_size
                     (const EndDeviceProtocol__Output *message)
{
  assert(message->base.descriptor == &end_device_protocol__output__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t end_device_protocol__output__pack
                     (const EndDeviceProtocol__Output *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &end_device_protocol__output__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t end_device_protocol__output__pack_to_buffer
                     (const EndDeviceProtocol__Output *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &end_device_protocol__output__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EndDeviceProtocol__Output *
       end_device_protocol__output__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EndDeviceProtocol__Output *)
     protobuf_c_message_unpack (&end_device_protocol__output__descriptor,
                                allocator, len, data);
}
void   end_device_protocol__output__free_unpacked
                     (EndDeviceProtocol__Output *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &end_device_protocol__output__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   end_device_protocol__expression__init
                     (EndDeviceProtocol__Expression         *message)
{
  static const EndDeviceProtocol__Expression init_value = END_DEVICE_PROTOCOL__EXPRESSION__INIT;
  *message = init_value;
}
size_t end_device_protocol__expression__get_packed_size
                     (const EndDeviceProtocol__Expression *message)
{
  assert(message->base.descriptor == &end_device_protocol__expression__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t end_device_protocol__expression__pack
                     (const EndDeviceProtocol__Expression *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &end_device_protocol__expression__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t end_device_protocol__expression__pack_to_buffer
                     (const EndDeviceProtocol__Expression *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &end_device_protocol__expression__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EndDeviceProtocol__Expression *
       end_device_protocol__expression__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EndDeviceProtocol__Expression *)
     protobuf_c_message_unpack (&end_device_protocol__expression__descriptor,
                                allocator, len, data);
}
void   end_device_protocol__expression__free_unpacked
                     (EndDeviceProtocol__Expression *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &end_device_protocol__expression__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   end_device_protocol__map_operation__init
                     (EndDeviceProtocol__MapOperation         *message)
{
  static const EndDeviceProtocol__MapOperation init_value = END_DEVICE_PROTOCOL__MAP_OPERATION__INIT;
  *message = init_value;
}
size_t end_device_protocol__map_operation__get_packed_size
                     (const EndDeviceProtocol__MapOperation *message)
{
  assert(message->base.descriptor == &end_device_protocol__map_operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t end_device_protocol__map_operation__pack
                     (const EndDeviceProtocol__MapOperation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &end_device_protocol__map_operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t end_device_protocol__map_operation__pack_to_buffer
                     (const EndDeviceProtocol__MapOperation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &end_device_protocol__map_operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EndDeviceProtocol__MapOperation *
       end_device_protocol__map_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EndDeviceProtocol__MapOperation *)
     protobuf_c_message_unpack (&end_device_protocol__map_operation__descriptor,
                                allocator, len, data);
}
void   end_device_protocol__map_operation__free_unpacked
                     (EndDeviceProtocol__MapOperation *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &end_device_protocol__map_operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   end_device_protocol__filter_operation__init
                     (EndDeviceProtocol__FilterOperation         *message)
{
  static const EndDeviceProtocol__FilterOperation init_value = END_DEVICE_PROTOCOL__FILTER_OPERATION__INIT;
  *message = init_value;
}
size_t end_device_protocol__filter_operation__get_packed_size
                     (const EndDeviceProtocol__FilterOperation *message)
{
  assert(message->base.descriptor == &end_device_protocol__filter_operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t end_device_protocol__filter_operation__pack
                     (const EndDeviceProtocol__FilterOperation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &end_device_protocol__filter_operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t end_device_protocol__filter_operation__pack_to_buffer
                     (const EndDeviceProtocol__FilterOperation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &end_device_protocol__filter_operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EndDeviceProtocol__FilterOperation *
       end_device_protocol__filter_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EndDeviceProtocol__FilterOperation *)
     protobuf_c_message_unpack (&end_device_protocol__filter_operation__descriptor,
                                allocator, len, data);
}
void   end_device_protocol__filter_operation__free_unpacked
                     (EndDeviceProtocol__FilterOperation *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &end_device_protocol__filter_operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   end_device_protocol__window_operation__init
                     (EndDeviceProtocol__WindowOperation         *message)
{
  static const EndDeviceProtocol__WindowOperation init_value = END_DEVICE_PROTOCOL__WINDOW_OPERATION__INIT;
  *message = init_value;
}
size_t end_device_protocol__window_operation__get_packed_size
                     (const EndDeviceProtocol__WindowOperation *message)
{
  assert(message->base.descriptor == &end_device_protocol__window_operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t end_device_protocol__window_operation__pack
                     (const EndDeviceProtocol__WindowOperation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &end_device_protocol__window_operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t end_device_protocol__window_operation__pack_to_buffer
                     (const EndDeviceProtocol__WindowOperation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &end_device_protocol__window_operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EndDeviceProtocol__WindowOperation *
       end_device_protocol__window_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EndDeviceProtocol__WindowOperation *)
     protobuf_c_message_unpack (&end_device_protocol__window_operation__descriptor,
                                allocator, len, data);
}
void   end_device_protocol__window_operation__free_unpacked
                     (EndDeviceProtocol__WindowOperation *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &end_device_protocol__window_operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   end_device_protocol__operation__init
                     (EndDeviceProtocol__Operation         *message)
{
  static const EndDeviceProtocol__Operation init_value = END_DEVICE_PROTOCOL__OPERATION__INIT;
  *message = init_value;
}
size_t end_device_protocol__operation__get_packed_size
                     (const EndDeviceProtocol__Operation *message)
{
  assert(message->base.descriptor == &end_device_protocol__operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t end_device_protocol__operation__pack
                     (const EndDeviceProtocol__Operation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &end_device_protocol__operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t end_device_protocol__operation__pack_to_buffer
                     (const EndDeviceProtocol__Operation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &end_device_protocol__operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EndDeviceProtocol__Operation *
       end_device_protocol__operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EndDeviceProtocol__Operation *)
     protobuf_c_message_unpack (&end_device_protocol__operation__descriptor,
                                allocator, len, data);
}
void   end_device_protocol__operation__free_unpacked
                     (EndDeviceProtocol__Operation *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &end_device_protocol__operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   end_device_protocol__query__init
                     (EndDeviceProtocol__Query         *message)
{
  static const EndDeviceProtocol__Query init_value = END_DEVICE_PROTOCOL__QUERY__INIT;
  *message = init_value;
}
size_t end_device_protocol__query__get_packed_size
                     (const EndDeviceProtocol__Query *message)
{
  assert(message->base.descriptor == &end_device_protocol__query__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t end_device_protocol__query__pack
                     (const EndDeviceProtocol__Query *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &end_device_protocol__query__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t end_device_protocol__query__pack_to_buffer
                     (const EndDeviceProtocol__Query *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &end_device_protocol__query__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EndDeviceProtocol__Query *
       end_device_protocol__query__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EndDeviceProtocol__Query *)
     protobuf_c_message_unpack (&end_device_protocol__query__descriptor,
                                allocator, len, data);
}
void   end_device_protocol__query__free_unpacked
                     (EndDeviceProtocol__Query *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &end_device_protocol__query__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   end_device_protocol__message__init
                     (EndDeviceProtocol__Message         *message)
{
  static const EndDeviceProtocol__Message init_value = END_DEVICE_PROTOCOL__MESSAGE__INIT;
  *message = init_value;
}
size_t end_device_protocol__message__get_packed_size
                     (const EndDeviceProtocol__Message *message)
{
  assert(message->base.descriptor == &end_device_protocol__message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t end_device_protocol__message__pack
                     (const EndDeviceProtocol__Message *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &end_device_protocol__message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t end_device_protocol__message__pack_to_buffer
                     (const EndDeviceProtocol__Message *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &end_device_protocol__message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EndDeviceProtocol__Message *
       end_device_protocol__message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EndDeviceProtocol__Message *)
     protobuf_c_message_unpack (&end_device_protocol__message__descriptor,
                                allocator, len, data);
}
void   end_device_protocol__message__free_unpacked
                     (EndDeviceProtocol__Message *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &end_device_protocol__message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor end_device_protocol__data__field_descriptors[11] =
{
  {
    "instruction",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(EndDeviceProtocol__Data, data_case),
    offsetof(EndDeviceProtocol__Data, instruction),
    &end_device_protocol__expression_instructions__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "_uint8",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(EndDeviceProtocol__Data, data_case),
    offsetof(EndDeviceProtocol__Data, _uint8),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "_uint16",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(EndDeviceProtocol__Data, data_case),
    offsetof(EndDeviceProtocol__Data, _uint16),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "_uint32",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(EndDeviceProtocol__Data, data_case),
    offsetof(EndDeviceProtocol__Data, _uint32),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "_uint64",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(EndDeviceProtocol__Data, data_case),
    offsetof(EndDeviceProtocol__Data, _uint64),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "_int8",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(EndDeviceProtocol__Data, data_case),
    offsetof(EndDeviceProtocol__Data, _int8),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "_int16",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(EndDeviceProtocol__Data, data_case),
    offsetof(EndDeviceProtocol__Data, _int16),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "_int32",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SINT32,
    offsetof(EndDeviceProtocol__Data, data_case),
    offsetof(EndDeviceProtocol__Data, _int32),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "_int64",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SINT64,
    offsetof(EndDeviceProtocol__Data, data_case),
    offsetof(EndDeviceProtocol__Data, _int64),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "_float",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(EndDeviceProtocol__Data, data_case),
    offsetof(EndDeviceProtocol__Data, _float),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "_double",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(EndDeviceProtocol__Data, data_case),
    offsetof(EndDeviceProtocol__Data, _double),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned end_device_protocol__data__field_indices_by_name[] = {
  10,   /* field[10] = _double */
  9,   /* field[9] = _float */
  6,   /* field[6] = _int16 */
  7,   /* field[7] = _int32 */
  8,   /* field[8] = _int64 */
  5,   /* field[5] = _int8 */
  2,   /* field[2] = _uint16 */
  3,   /* field[3] = _uint32 */
  4,   /* field[4] = _uint64 */
  1,   /* field[1] = _uint8 */
  0,   /* field[0] = instruction */
};
static const ProtobufCIntRange end_device_protocol__data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor end_device_protocol__data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EndDeviceProtocol.Data",
  "Data",
  "EndDeviceProtocol__Data",
  "EndDeviceProtocol",
  sizeof(EndDeviceProtocol__Data),
  11,
  end_device_protocol__data__field_descriptors,
  end_device_protocol__data__field_indices_by_name,
  1,  end_device_protocol__data__number_ranges,
  (ProtobufCMessageInit) end_device_protocol__data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor end_device_protocol__output__query_response__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(EndDeviceProtocol__Output__QueryResponse, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "response",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EndDeviceProtocol__Output__QueryResponse, n_response),
    offsetof(EndDeviceProtocol__Output__QueryResponse, response),
    &end_device_protocol__data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned end_device_protocol__output__query_response__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = response */
};
static const ProtobufCIntRange end_device_protocol__output__query_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor end_device_protocol__output__query_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EndDeviceProtocol.Output.QueryResponse",
  "QueryResponse",
  "EndDeviceProtocol__Output__QueryResponse",
  "EndDeviceProtocol",
  sizeof(EndDeviceProtocol__Output__QueryResponse),
  2,
  end_device_protocol__output__query_response__field_descriptors,
  end_device_protocol__output__query_response__field_indices_by_name,
  1,  end_device_protocol__output__query_response__number_ranges,
  (ProtobufCMessageInit) end_device_protocol__output__query_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor end_device_protocol__output__field_descriptors[1] =
{
  {
    "responses",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EndDeviceProtocol__Output, n_responses),
    offsetof(EndDeviceProtocol__Output, responses),
    &end_device_protocol__output__query_response__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned end_device_protocol__output__field_indices_by_name[] = {
  0,   /* field[0] = responses */
};
static const ProtobufCIntRange end_device_protocol__output__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor end_device_protocol__output__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EndDeviceProtocol.Output",
  "Output",
  "EndDeviceProtocol__Output",
  "EndDeviceProtocol",
  sizeof(EndDeviceProtocol__Output),
  1,
  end_device_protocol__output__field_descriptors,
  end_device_protocol__output__field_indices_by_name,
  1,  end_device_protocol__output__number_ranges,
  (ProtobufCMessageInit) end_device_protocol__output__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor end_device_protocol__expression__field_descriptors[1] =
{
  {
    "instructions",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EndDeviceProtocol__Expression, n_instructions),
    offsetof(EndDeviceProtocol__Expression, instructions),
    &end_device_protocol__data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned end_device_protocol__expression__field_indices_by_name[] = {
  0,   /* field[0] = instructions */
};
static const ProtobufCIntRange end_device_protocol__expression__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor end_device_protocol__expression__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EndDeviceProtocol.Expression",
  "Expression",
  "EndDeviceProtocol__Expression",
  "EndDeviceProtocol",
  sizeof(EndDeviceProtocol__Expression),
  1,
  end_device_protocol__expression__field_descriptors,
  end_device_protocol__expression__field_indices_by_name,
  1,  end_device_protocol__expression__number_ranges,
  (ProtobufCMessageInit) end_device_protocol__expression__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor end_device_protocol__map_operation__field_descriptors[2] =
{
  {
    "function",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EndDeviceProtocol__MapOperation, n_function),
    offsetof(EndDeviceProtocol__MapOperation, function),
    &end_device_protocol__data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attribute",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(EndDeviceProtocol__MapOperation, attribute),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned end_device_protocol__map_operation__field_indices_by_name[] = {
  1,   /* field[1] = attribute */
  0,   /* field[0] = function */
};
static const ProtobufCIntRange end_device_protocol__map_operation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor end_device_protocol__map_operation__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EndDeviceProtocol.MapOperation",
  "MapOperation",
  "EndDeviceProtocol__MapOperation",
  "EndDeviceProtocol",
  sizeof(EndDeviceProtocol__MapOperation),
  2,
  end_device_protocol__map_operation__field_descriptors,
  end_device_protocol__map_operation__field_indices_by_name,
  1,  end_device_protocol__map_operation__number_ranges,
  (ProtobufCMessageInit) end_device_protocol__map_operation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor end_device_protocol__filter_operation__field_descriptors[1] =
{
  {
    "predicate",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EndDeviceProtocol__FilterOperation, n_predicate),
    offsetof(EndDeviceProtocol__FilterOperation, predicate),
    &end_device_protocol__data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned end_device_protocol__filter_operation__field_indices_by_name[] = {
  0,   /* field[0] = predicate */
};
static const ProtobufCIntRange end_device_protocol__filter_operation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor end_device_protocol__filter_operation__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EndDeviceProtocol.FilterOperation",
  "FilterOperation",
  "EndDeviceProtocol__FilterOperation",
  "EndDeviceProtocol",
  sizeof(EndDeviceProtocol__FilterOperation),
  1,
  end_device_protocol__filter_operation__field_descriptors,
  end_device_protocol__filter_operation__field_indices_by_name,
  1,  end_device_protocol__filter_operation__number_ranges,
  (ProtobufCMessageInit) end_device_protocol__filter_operation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor end_device_protocol__window_operation__field_descriptors[7] =
{
  {
    "size",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(EndDeviceProtocol__WindowOperation, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sizeType",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(EndDeviceProtocol__WindowOperation, sizetype),
    &end_device_protocol__window_size_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "aggregationType",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(EndDeviceProtocol__WindowOperation, aggregationtype),
    &end_device_protocol__window_aggregation_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "startAttribute",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(EndDeviceProtocol__WindowOperation, startattribute),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "endAttribute",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(EndDeviceProtocol__WindowOperation, endattribute),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resultAttribute",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(EndDeviceProtocol__WindowOperation, resultattribute),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "readAttribute",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(EndDeviceProtocol__WindowOperation, readattribute),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned end_device_protocol__window_operation__field_indices_by_name[] = {
  2,   /* field[2] = aggregationType */
  4,   /* field[4] = endAttribute */
  6,   /* field[6] = readAttribute */
  5,   /* field[5] = resultAttribute */
  0,   /* field[0] = size */
  1,   /* field[1] = sizeType */
  3,   /* field[3] = startAttribute */
};
static const ProtobufCIntRange end_device_protocol__window_operation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor end_device_protocol__window_operation__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EndDeviceProtocol.WindowOperation",
  "WindowOperation",
  "EndDeviceProtocol__WindowOperation",
  "EndDeviceProtocol",
  sizeof(EndDeviceProtocol__WindowOperation),
  7,
  end_device_protocol__window_operation__field_descriptors,
  end_device_protocol__window_operation__field_indices_by_name,
  1,  end_device_protocol__window_operation__number_ranges,
  (ProtobufCMessageInit) end_device_protocol__window_operation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor end_device_protocol__operation__field_descriptors[3] =
{
  {
    "map",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EndDeviceProtocol__Operation, operation_case),
    offsetof(EndDeviceProtocol__Operation, map),
    &end_device_protocol__map_operation__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "filter",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EndDeviceProtocol__Operation, operation_case),
    offsetof(EndDeviceProtocol__Operation, filter),
    &end_device_protocol__filter_operation__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "window",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EndDeviceProtocol__Operation, operation_case),
    offsetof(EndDeviceProtocol__Operation, window),
    &end_device_protocol__window_operation__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned end_device_protocol__operation__field_indices_by_name[] = {
  1,   /* field[1] = filter */
  0,   /* field[0] = map */
  2,   /* field[2] = window */
};
static const ProtobufCIntRange end_device_protocol__operation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor end_device_protocol__operation__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EndDeviceProtocol.Operation",
  "Operation",
  "EndDeviceProtocol__Operation",
  "EndDeviceProtocol",
  sizeof(EndDeviceProtocol__Operation),
  3,
  end_device_protocol__operation__field_descriptors,
  end_device_protocol__operation__field_indices_by_name,
  1,  end_device_protocol__operation__number_ranges,
  (ProtobufCMessageInit) end_device_protocol__operation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor end_device_protocol__query__field_descriptors[1] =
{
  {
    "operations",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EndDeviceProtocol__Query, n_operations),
    offsetof(EndDeviceProtocol__Query, operations),
    &end_device_protocol__operation__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned end_device_protocol__query__field_indices_by_name[] = {
  0,   /* field[0] = operations */
};
static const ProtobufCIntRange end_device_protocol__query__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor end_device_protocol__query__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EndDeviceProtocol.Query",
  "Query",
  "EndDeviceProtocol__Query",
  "EndDeviceProtocol",
  sizeof(EndDeviceProtocol__Query),
  1,
  end_device_protocol__query__field_descriptors,
  end_device_protocol__query__field_indices_by_name,
  1,  end_device_protocol__query__number_ranges,
  (ProtobufCMessageInit) end_device_protocol__query__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor end_device_protocol__message__field_descriptors[1] =
{
  {
    "queries",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EndDeviceProtocol__Message, n_queries),
    offsetof(EndDeviceProtocol__Message, queries),
    &end_device_protocol__query__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned end_device_protocol__message__field_indices_by_name[] = {
  0,   /* field[0] = queries */
};
static const ProtobufCIntRange end_device_protocol__message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor end_device_protocol__message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EndDeviceProtocol.Message",
  "Message",
  "EndDeviceProtocol__Message",
  "EndDeviceProtocol",
  sizeof(EndDeviceProtocol__Message),
  1,
  end_device_protocol__message__field_descriptors,
  end_device_protocol__message__field_indices_by_name,
  1,  end_device_protocol__message__number_ranges,
  (ProtobufCMessageInit) end_device_protocol__message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue end_device_protocol__expression_instructions__enum_values_by_number[13] =
{
  { "CONST", "END_DEVICE_PROTOCOL__EXPRESSION_INSTRUCTIONS__CONST", 0 },
  { "VAR", "END_DEVICE_PROTOCOL__EXPRESSION_INSTRUCTIONS__VAR", 1 },
  { "AND", "END_DEVICE_PROTOCOL__EXPRESSION_INSTRUCTIONS__AND", 2 },
  { "OR", "END_DEVICE_PROTOCOL__EXPRESSION_INSTRUCTIONS__OR", 3 },
  { "NOT", "END_DEVICE_PROTOCOL__EXPRESSION_INSTRUCTIONS__NOT", 4 },
  { "LT", "END_DEVICE_PROTOCOL__EXPRESSION_INSTRUCTIONS__LT", 5 },
  { "GT", "END_DEVICE_PROTOCOL__EXPRESSION_INSTRUCTIONS__GT", 6 },
  { "EQ", "END_DEVICE_PROTOCOL__EXPRESSION_INSTRUCTIONS__EQ", 7 },
  { "ADD", "END_DEVICE_PROTOCOL__EXPRESSION_INSTRUCTIONS__ADD", 8 },
  { "SUB", "END_DEVICE_PROTOCOL__EXPRESSION_INSTRUCTIONS__SUB", 9 },
  { "MUL", "END_DEVICE_PROTOCOL__EXPRESSION_INSTRUCTIONS__MUL", 10 },
  { "DIV", "END_DEVICE_PROTOCOL__EXPRESSION_INSTRUCTIONS__DIV", 11 },
  { "MOD", "END_DEVICE_PROTOCOL__EXPRESSION_INSTRUCTIONS__MOD", 12 },
};
static const ProtobufCIntRange end_device_protocol__expression_instructions__value_ranges[] = {
{0, 0},{0, 13}
};
static const ProtobufCEnumValueIndex end_device_protocol__expression_instructions__enum_values_by_name[13] =
{
  { "ADD", 8 },
  { "AND", 2 },
  { "CONST", 0 },
  { "DIV", 11 },
  { "EQ", 7 },
  { "GT", 6 },
  { "LT", 5 },
  { "MOD", 12 },
  { "MUL", 10 },
  { "NOT", 4 },
  { "OR", 3 },
  { "SUB", 9 },
  { "VAR", 1 },
};
const ProtobufCEnumDescriptor end_device_protocol__expression_instructions__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EndDeviceProtocol.ExpressionInstructions",
  "ExpressionInstructions",
  "EndDeviceProtocol__ExpressionInstructions",
  "EndDeviceProtocol",
  13,
  end_device_protocol__expression_instructions__enum_values_by_number,
  13,
  end_device_protocol__expression_instructions__enum_values_by_name,
  1,
  end_device_protocol__expression_instructions__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue end_device_protocol__window_aggregation_type__enum_values_by_number[5] =
{
  { "MIN", "END_DEVICE_PROTOCOL__WINDOW_AGGREGATION_TYPE__MIN", 0 },
  { "MAX", "END_DEVICE_PROTOCOL__WINDOW_AGGREGATION_TYPE__MAX", 1 },
  { "SUM", "END_DEVICE_PROTOCOL__WINDOW_AGGREGATION_TYPE__SUM", 2 },
  { "AVG", "END_DEVICE_PROTOCOL__WINDOW_AGGREGATION_TYPE__AVG", 3 },
  { "COUNT", "END_DEVICE_PROTOCOL__WINDOW_AGGREGATION_TYPE__COUNT", 4 },
};
static const ProtobufCIntRange end_device_protocol__window_aggregation_type__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex end_device_protocol__window_aggregation_type__enum_values_by_name[5] =
{
  { "AVG", 3 },
  { "COUNT", 4 },
  { "MAX", 1 },
  { "MIN", 0 },
  { "SUM", 2 },
};
const ProtobufCEnumDescriptor end_device_protocol__window_aggregation_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EndDeviceProtocol.WindowAggregationType",
  "WindowAggregationType",
  "EndDeviceProtocol__WindowAggregationType",
  "EndDeviceProtocol",
  5,
  end_device_protocol__window_aggregation_type__enum_values_by_number,
  5,
  end_device_protocol__window_aggregation_type__enum_values_by_name,
  1,
  end_device_protocol__window_aggregation_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue end_device_protocol__window_size_type__enum_values_by_number[2] =
{
  { "TIMEBASED", "END_DEVICE_PROTOCOL__WINDOW_SIZE_TYPE__TIMEBASED", 0 },
  { "COUNTBASED", "END_DEVICE_PROTOCOL__WINDOW_SIZE_TYPE__COUNTBASED", 1 },
};
static const ProtobufCIntRange end_device_protocol__window_size_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex end_device_protocol__window_size_type__enum_values_by_name[2] =
{
  { "COUNTBASED", 1 },
  { "TIMEBASED", 0 },
};
const ProtobufCEnumDescriptor end_device_protocol__window_size_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EndDeviceProtocol.WindowSizeType",
  "WindowSizeType",
  "EndDeviceProtocol__WindowSizeType",
  "EndDeviceProtocol",
  2,
  end_device_protocol__window_size_type__enum_values_by_number,
  2,
  end_device_protocol__window_size_type__enum_values_by_name,
  1,
  end_device_protocol__window_size_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
