/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: foo.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "foo.pb-c.h"
void   foo__bar__init
                     (Foo__Bar         *message)
{
  static const Foo__Bar init_value = FOO__BAR__INIT;
  *message = init_value;
}
size_t foo__bar__get_packed_size
                     (const Foo__Bar *message)
{
  assert(message->base.descriptor == &foo__bar__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t foo__bar__pack
                     (const Foo__Bar *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &foo__bar__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t foo__bar__pack_to_buffer
                     (const Foo__Bar *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &foo__bar__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Foo__Bar *
       foo__bar__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Foo__Bar *)
     protobuf_c_message_unpack (&foo__bar__descriptor,
                                allocator, len, data);
}
void   foo__bar__free_unpacked
                     (Foo__Bar *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &foo__bar__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor foo__bar__field_descriptors[1] =
{
  {
    "baz",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Foo__Bar, baz),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned foo__bar__field_indices_by_name[] = {
  0,   /* field[0] = baz */
};
static const ProtobufCIntRange foo__bar__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor foo__bar__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Foo.Bar",
  "Bar",
  "Foo__Bar",
  "Foo",
  sizeof(Foo__Bar),
  1,
  foo__bar__field_descriptors,
  foo__bar__field_indices_by_name,
  1,  foo__bar__number_ranges,
  (ProtobufCMessageInit) foo__bar__init,
  NULL,NULL,NULL    /* reserved[123] */
};
