/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: foo.proto */

#ifndef PROTOBUF_C_foo_2eproto__INCLUDED
#define PROTOBUF_C_foo_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Foo__Bar Foo__Bar;


/* --- enums --- */


/* --- messages --- */

struct  Foo__Bar
{
  ProtobufCMessage base;
  char *baz;
};
#define FOO__BAR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&foo__bar__descriptor) \
    , (char *)protobuf_c_empty_string }


/* Foo__Bar methods */
void   foo__bar__init
                     (Foo__Bar         *message);
size_t foo__bar__get_packed_size
                     (const Foo__Bar   *message);
size_t foo__bar__pack
                     (const Foo__Bar   *message,
                      uint8_t             *out);
size_t foo__bar__pack_to_buffer
                     (const Foo__Bar   *message,
                      ProtobufCBuffer     *buffer);
Foo__Bar *
       foo__bar__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   foo__bar__free_unpacked
                     (Foo__Bar *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Foo__Bar_Closure)
                 (const Foo__Bar *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor foo__bar__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_foo_2eproto__INCLUDED */
