#include <stdio.h>
#include <stdlib.h>

#include "foo.pb-c.h" // generated by protoc-c

int main(int argc, char** argv) {
  printf("ProtoTest main\n");

  Foo__Bar bar;
  foo__bar__init(&bar); //Initialize the Foo__Bar instance
  void *buf; // buffer to hold serialized data
  unsigned len; // length of serialized data

  if(argc != 2){
    printf("You need 1 argument\n");
    return 1;
  }

  bar.baz = argv[1]; //Converts the string argument str to an integer (type int).
  len = foo__bar__get_packed_size(&bar); //Get the packed size of bar/serialized data length

  buf = malloc(len);
  foo__bar__pack(&bar, buf); //Serialize bar into the buffer buf

  printf("Writng %d serialized bytes\n", len);
  numWritten = fwrite(buf,len, sizeof(buf), stdout); //Write the buffer to stdout
  printf("Wrote %d serialized bytes to stdout\n", numWritten);

  free(buf); // Free the allocated serialized data buffer

  printf("Finished main\n");

  return 0;
}